spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/uaa
    username: ${database.username:uaauser}
    password: ${database.password:uaapass}
    type: org.apache.tomcat.jdbc.pool.DataSource