database.platform=postgresql
database.driverClassName=org.postgresql.Driver
database.url=jdbc:postgresql://localhost:5432/uaa
database.username=uaauser
database.password=uaapass
database.maxactive=100
database.maxidle=10
database.removeabandoned=false
database.abandonedtimeout=300
database.logabandoned=true